apiVersion: v1
items:
- apiVersion: v1
  data:
    root-password: bXlzcWwxMjM=
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"mysql-secret","namespace":"middleware"},"stringData":{"root-password":"mysql123"},"type":"Opaque"}
    creationTimestamp: "2026-05-16T17:44:55Z"
    name: mysql-secret
    namespace: middleware
    resourceVersion: "101297"
    uid: 3bede7bd-0f78-4ad0-8fe3-7ea7ccce2e04
  type: Opaque
kind: List
metadata:
  resourceVersion: ""

